# Configuration fragment for a solid bridge between case and wrist rest.

secondaries:
  wrb-case:
    anchoring:
      anchor: m03
      side: SSE
      segment: 3
    translation: [-16, 0, -10]
  wrb-rest:
    anchoring:
      anchor: plinth-left
    translation: [0, 0, -3]
  wrb1a:
    anchoring:
      anchor: wrb-case
  wrb1b:
    anchoring:
      anchor: wrb1a
    translation: [10, 0, 8]
  wrb1c:
    anchoring:
      anchor: wrb1a
    translation: [20, 0, 8]
  wrb1d:
    anchoring:
      anchor: wrb1a
    translation: [30, 0, 0]
  wrb2a:
    anchoring:
      anchor: wrb1a
    translation: [5, -15, 0]
  wrb2b:
    anchoring:
      anchor: wrb1b
    translation: [2, -15, -5]
  wrb2c:
    anchoring:
      anchor: wrb1c
    translation: [-2, -15, -5]
  wrb2d:
    anchoring:
      anchor: wrb1d
    translation: [-5, -15, 0]
  wrb3a:
    anchoring:
      anchor: wrb2a
    translation: [0, -25, 0]
  wrb3b:
    anchoring:
      anchor: wrb2b
    translation: [0, -25, 0]
  wrb3c:
    anchoring:
      anchor: wrb2c
    translation: [0, -25, 0]
  wrb3d:
    anchoring:
      anchor: wrb2d
    translation: [0, -25, 0]
  wrb4a:
    anchoring:
      anchor: wrb1a
    translation: [0, -55, 0]
  wrb4b:
    anchoring:
      anchor: wrb1b
    translation: [0, -55, 0]
  wrb4c:
    anchoring:
      anchor: wrb1c
    translation: [0, -55, 0]
  wrb4d:
    anchoring:
      anchor: wrb1d
    translation: [0, -55, 0]
  wrb5b:
    anchoring:
      anchor: wrb4b
    translation: [0, -10, 0]
  wrb5c:
    anchoring:
      anchor: wrb4c
    translation: [0, -10, 0]
tweaks:
  wrist-rest-bridge-main-body:
    - chunk-size: 2
      at-ground: true
      hull-around:
      - hull-around:
        - [wrb1a]
        - [wrb1b]
        - [wrb1c]
        - [wrb1d]
      - hull-around:
        - [wrb2a]
        - [wrb2b]
        - [wrb2c]
        - [wrb2d]
  wrist-rest-bridge-middle:
    - chunk-size: 2
      at-ground: true
      hull-around:
      - hull-around:
        - [wrb2a]
        - [wrb2b]
        - [wrb2c]
        - [wrb2d]
      - hull-around:
        - [wrb3a]
        - [wrb3b]
        - [wrb3c]
        - [wrb3d]
  wrist-rest-bridge-rest:
    - chunk-size: 2
      at-ground: true
      hull-around:
      - hull-around:
        - [wrb3a]
        - [wrb3b]
        - [wrb3c]
        - [wrb3d]
      - hull-around:
        - [wrb4a]
        - [wrb4b]
        - [wrb4c]
        - [wrb4d]
      - hull-around:
        - [wrb-rest]
        - [plinth-mid0]
        - [plinth-mid1]
        - [wrb5b]
        - [wrb5c]
wrist-rest:
  include: true
  style: solid
